### ISSUE TITLE
Syntax Error since 3.0.12

### ISSUE THREAD

**Issue by fr33tux** [opensolutions/ViMbAdmin#143]
Since the v3.0.12, I'm getting the following issue. It throws the same error on a new installation, and with the latest Smarty version. It's running with php 5.6 (on Debian Jessie).

**SmartyCompilerException**

**File**
    *ViMbAdmin.git/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php*

**Line**
    *79*

**Message**

```
    Syntax error in template "ViMbAdmin.git/application/views/domain/list.phtml" on line 79 "<{$action.tagName} {foreach $action as $attrib => $value}{if !in_array( $attrib, [ "tagName", "child"] )}{$attrib}="{$value|replace:'%id%':$oid}" {/if}{/foreach}>" unknown modifier "replace"

```
**Code**
    *0*

**Trace**

```
#0 ViMbAdmin.git/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_modifier.php(133): Smarty_Internal_TemplateCompilerBase->trigger_template_error('unknown modifie...', 79)
#1 ViMbAdmin.git/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(556): Smarty_Internal_Compile_Private_Modifier->compile(Array, Object(Smarty_Internal_SmartyTemplateCompiler), Array, NULL, NULL)
#2 ViMbAdmin.git/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(337): Smarty_Internal_TemplateCompilerBase->callTagCompiler('private_modifie...', Array, Array)
#3 ViMbAdmin.git/vendor/smarty/smarty/libs/sysplugins/smarty_internal_compile_private_print_expression.php(65): Smarty_Internal_TemplateCompilerBase->compileTag('private_modifie...', Array, Array)
#4 ViMbAdmin.git/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(556): Smarty_Internal_Compile_Private_Print_Expression->compile(Array, Object(Smarty_Internal_SmartyTemplateCompiler), Array, NULL, NULL)
#5 ViMbAdmin.git/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(337): Smarty_Internal_TemplateCompilerBase->callTagCompiler('private_print_e...', Array, Array)
#6 ViMbAdmin.git/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templateparser.php(2353): Smarty_Internal_TemplateCompilerBase->compileTag('private_print_e...', Array, Array)
#7 ViMbAdmin.git/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templateparser.php(3093): Smarty_Internal_Templateparser->yy_r29()
#8 ViMbAdmin.git/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templateparser.php(3191): Smarty_Internal_Templateparser->yy_reduce(29)
#9 ViMbAdmin.git/vendor/smarty/smarty/libs/sysplugins/smarty_internal_smartytemplatecompiler.php(111): Smarty_Internal_Templateparser->doParse(3, '}')
#10 ViMbAdmin.git/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php(273): Smarty_Internal_SmartyTemplateCompiler->doCompile('{tmplinclude fi...')
#11 ViMbAdmin.git/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(186): Smarty_Internal_TemplateCompilerBase->compileTemplate(Object(Smarty_Internal_Template))
#12 ViMbAdmin.git/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(149): Smarty_Internal_Template->compileTemplateSource()
#13 ViMbAdmin.git/vendor/opensolutions/oss-framework/src/OSS/View/Smarty.php(300): Smarty_Internal_TemplateBase->fetch('domain/list.pht...')
#14 ViMbAdmin.git/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(912): OSS_View_Smarty->render('domain/list.pht...')
#15 ViMbAdmin.git/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('domain/list.pht...', NULL)
#16 ViMbAdmin.git/vendor/zendframework/zendframework1/library/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
#17 ViMbAdmin.git/vendor/zendframework/zendframework1/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#18 ViMbAdmin.git/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#19 ViMbAdmin.git/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('listAction')
#20 ViMbAdmin.git/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#21 ViMbAdmin.git/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#22 ViMbAdmin.git/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#23 ViMbAdmin.git/public/index.php(34): Zend_Application->run()
#24 {main}
```

**Comment by mirrom** [comment]
I've got the exact same issue on version 3.0.15 (after upgrading from version 3.0.8) with php 5.4 and 5.6 on Debian Wheezy.

@barryo Did you manage to fix this or did you just close the ticket?

@fr33tux What did you do to solve this issue?

**Comment by mirrom** [comment]
Sorry, my bad! Id forgot to update `application.ini` to the latest version...
