### ISSUE TITLE
Doctrine\DBAL\Exception\TableNotFoundException

### ISSUE THREAD

**Issue by pixelchrome** [opensolutions/ViMbAdmin#170]
After upgrading my FreeBSD php to version 5.6 (and several other updates), I found out that ViMbAdmin no longer worked as expected ;-)

Any idea what happened and how to fix this?

# Uh oh! Unexpected Error!

..

# Doctrine\DBAL\Exception\TableNotFoundException

## File
/opt/vimbadmin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
Line
57
## Message
An exception occurred while executing 'SELECT COUNT(a0_.id) AS sclr_0 FROM admin.admin a0_': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin.admin' doesn't exist
## Code
0
## Trace

```
#0 /opt/vimbadmin/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(142): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /opt/vimbadmin/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'An exception oc...')
#2 /opt/vimbadmin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(828): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT COUNT(a0...', Array)
#3 /opt/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery('SELECT COUNT(a0...', Array, Array, NULL)
#4 /opt/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(323): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)
#5 /opt/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(968): Doctrine\ORM\Query->_doExecute()
#6 /opt/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(923): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 4)
#7 /opt/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(803): Doctrine\ORM\AbstractQuery->execute(NULL, 4)
#8 /opt/vimbadmin/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(832): Doctrine\ORM\AbstractQuery->getSingleResult(4)
#9 /opt/vimbadmin/application/Repositories/Admin.php(27): Doctrine\ORM\AbstractQuery->getSingleScalarResult()
#10 /opt/vimbadmin/application/controllers/AuthController.php(52): Repositories\Admin->getCount()
#11 /opt/vimbadmin/vendor/opensolutions/oss-framework/src/OSS/Controller/Trait/Auth.php(99): AuthController->_preLogin()
#12 /opt/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): AuthController->loginAction()
#13 /opt/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('loginAction')
#14 /opt/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#15 /opt/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#16 /opt/vimbadmin/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#17 /opt/vimbadmin/public/index.php(34): Zend_Application->run()
#18 {main}
```

**Comment by pixelchrome** [comment]
I've reinstalled it a second time... and now it works (via PHP Composer). Don't know what went wrong during the first time (via Git clone).

**Comment by GaneshKandu** [comment]
# Hi Getting Same Error **[#170](https://github.com/opensolutions/ViMbAdmin/issues/170#issue-140503966)**
My database is not populated its empty any idea what to do?

- **Notice:** Use of undefined constant DS - assumed 'DS' in **vimbadmin/library/ViMbAdmin/Smarty/functions/modifier.date_formatter.php** on line **47**

- Got Following Error During Installation of Composer

![untitled](https://cloud.githubusercontent.com/assets/12833130/26492983/acb4e7ac-4234-11e7-99e0-ef46eff0d92e.png)

# System: 
- mysql Server version: 5.5.53
- Apache/2.2.31 (Unix)
- PHP Version 7.0.12
