### ISSUE TITLE
Table 'vimbadmin.config' doesn't exist'

### ISSUE THREAD

**Issue by DasLampe** [opensolutions/ViMbAdmin#171]
With fresh installation (via composer) I get this error:

````
PHP Fatal error:  Uncaught exception 'Doctrine_Connection_Mysql_Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'vimbadmin.config' doesn't exist' in /usr/local/vimbadmin/library/Doctrine/Doctrine/Connection.php:1082\nStack trace:\n#0 /usr/local/vimbadmin/library/Doctrine/Doctrine/Connection/Statement.php(269): Doctrine_Connection->rethrowException(Object(PDOException), Object(Doctrine_Connection_Statement))\n#1 /usr/local/vimbadmin/library/Doctrine/Doctrine/Connection.php(1006): Doctrine_Connection_Statement->execute(Array)\n#2 /usr/local/vimbadmin/library/Doctrine/Doctrine/Query/Abstract.php(983): Doctrine_Connection->execute('SELECT c.value ...', Array)\n#3 /usr/local/vimbadmin/library/Doctrine/Doctrine/Query/Abstract.php(1033): Doctrine_Query_Abstract->_execute(NULL)\n#4 /usr/local/vimbadmin/application/models/ConfigTable.php(67): Doctrine_Query_Abstract->execute(NULL, 6)\n#5 /usr/local/vimbadmin/library/ViMbAdmin/Controller/Action.php(382): ConfigTable::getValue('version_last_ch...')\n#6 /usr/loc in /usr/local/vimbadmin/library/Zend/Controller/Plugin/Broker.php on line 336
```

mysql > SHOW TABLES shows this
```
+---------------------+
| Tables_in_vimbadmin |
+---------------------+
| admin               |
| admin_pref          |
| alias               |
| alias_pref          |
| archive             |
| dbversion           |
| directory_entry     |
| domain              |
| domain_admins       |
| domain_pref         |
| log                 |
| mailbox             |
| mailbox_pref        |
| remember_me         |
+---------------------+
```

**Comment by DasLampe** [comment]
My fault, sorry!

Had 2 instances and apache refer to the old one.
