### ISSUE TITLE
Redis Zend Exception

### ISSUE THREAD

**Issue by kai-cool-dev** [opensolutions/ViMbAdmin#255]
Hello,

I am currently adding Redis Support to all my webservers (for session handling) and I experienced that ViMbAdmin throws an Zend Exception:

```
Fatal error: Uncaught RedisException: Connection closed in /var/www/vhost/[redacted]/web/vendor/zendframework/zendframework1/library/Zend/Session.php:482 Stack trace: #0 /var/www/vhost/[redacted]/web/vendor/zendframework/zendframework1/library/Zend/Session.php(482): session_start() #1 /var/www/vhost/[redacted]/web/vendor/zendframework/zendframework1/library/Zend/Session/Namespace.php(143): Zend_Session::start(true) #2 /var/www/vhost/[redacted]/web/vendor/opensolutions/oss-framework/src/OSS/Resource/Namespace.php(81): Zend_Session_Namespace->__construct('Application') #3 /var/www/vhost/[redacted]/web/vendor/opensolutions/oss-framework/src/OSS/Resource/Namespace.php(63): OSS_Resource_Namespace->getSession() #4 /var/www/vhost/[redacted]/web/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/BootstrapAbstract.php(695): OSS_Resource_Namespace->init() #5 /var/www/vhost/[redacted]/web/vendor/zendframework/zendframework1/librar in /var/www/vhost/[redacted]/web/vendor/zendframework/zendframework1/library/Zend/Session.php on line 482
```

All other Applications on this server (debian stretch) are working fine, so I don't think that the webserver (nginx 15) or php (php7.2-fpm) causing the problem. I'm using version 3.0.15 of ViMbAdmin.

Kind regards

**Comment by barryo** [comment]
Hi,

I'm afraid ZF1 is a legacy framework at this stage and I really don't know if it does or can support Redis.

Sorry!
