### ISSUE TITLE
Zend unable to resolve plugin "auth" in 3.2.1

### ISSUE THREAD

**Issue by fweep** [opensolutions/ViMbAdmin#269]
I had a working ViMbAdmin installation (I forget which version, but it was new around Dec 2019). I just installed 3.2.1, following the upgrade instructions, and now I get this error trying to view the home page:

```
Fatal error: Uncaught Zend_Application_Bootstrap_Exception: Unable to resolve plugin "auth"; no corresponding plugin with that name in /var/www/admin.example.com/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php:340 Stack trace: #0 /var/www/admin.example.com/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php(392): Zend_Application_Bootstrap_BootstrapAbstract->getPluginResource('auth') #1 /var/www/admin.example.com/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php(404): Zend_Application_Bootstrap_BootstrapAbstract->getPluginResources() #2 /var/www/admin.example.com/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php(637): Zend_Application_Bootstrap_BootstrapAbstract->getPluginResourceNames() #3 /var/www/admin.example.com/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php(598): Zend_Application_Bootstrap_Bootstr in /var/www/admin.example.com/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/BootstrapAbstract.php on line 340
```

I ran `composer` and it looks ok:

```
$ composer install --prefer-dist --no-dev

Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
```

My PHP knowledge is limited, so I'm not sure what the right way to resolve this is.

I downgraded to 3.1.1 and my installation is working again.

**Comment by barryo** [comment]
Hi @fweep 

I had no issues myself upgrading from a number of different versions. 

Did you make the changes in `application.ini` as advised in [these notes](https://github.com/opensolutions/ViMbAdmin/releases/tag/3.2.0)?

If yes, they maybe a diff between `application.ini` and `application.ini.dist` might show up other changes?

**Comment by fweep** [comment]
Thanks, that fixed it! I hadn't gone through the prior release notes.
