### ISSUE TITLE
PostgreSQL: Initial setup of database leads to an error

### ISSUE THREAD

**Issue by frlan** [opensolutions/ViMbAdmin#311]
```
$ bin/doctrine2-cli.php orm:schema-tool:create

 !                                                                                               
 ! [CAUTION] This operation should not be executed in a production environment!                  
 !                                                                                               

 Creating database schema...


In ToolsException.php line 35:
                                                                                                
  Schema-Tool failed with Error 'An exception occurred while executing 'CREATE TABLE dbversion  
   (id INT NOT NULL, version INT NOT NULL, name VARCHAR(255) NOT NULL, applied_on TIMESTAMP(0)  
   WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))':                                               
                                                                                                
  SQLSTATE[42P07]: Duplicate table: 7 FEHLER:  Relation »dbversion« existiert bereits' while e  
  xecuting DDL: CREATE TABLE dbversion (id INT NOT NULL, version INT NOT NULL, name VARCHAR(25  
  5) NOT NULL, applied_on TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))             
                                                                                                

In AbstractPostgreSQLDriver.php line 85:
                                                                                                
  An exception occurred while executing 'CREATE TABLE dbversion (id INT NOT NULL, version INT   
  NOT NULL, name VARCHAR(255) NOT NULL, applied_on TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PR  
  IMARY KEY(id))':                                                                              
                                                                                                
  SQLSTATE[42P07]: Duplicate table: 7 FEHLER:  Relation »dbversion« existiert bereits  
```
(Relation »dbversion« existiert bereits   = Relation already exists)

Source from composer

**Comment by mathiashro** [comment]
Somehow kind of the same issue, any idea? Using recent stable (3.4.1):

```
vimbadmin# ./bin/doctrine2-cli.php orm:schema-tool:create
PHP Fatal error:  Uncaught Zend_Config_Exception: Cannot create sub-key for 'email' as key already exists in /var/www/vimbadmin/vendor/shardj/zf1-future/library/Zend/Config/Ini.php:304
Stack trace:
#0 /var/www/vimbadmin/vendor/shardj/zf1-future/library/Zend/Config/Ini.php(306): Zend_Config_Ini->_processKey()
#1 /var/www/vimbadmin/vendor/shardj/zf1-future/library/Zend/Config/Ini.php(271): Zend_Config_Ini->_processKey()
#2 /var/www/vimbadmin/vendor/shardj/zf1-future/library/Zend/Config/Ini.php(261): Zend_Config_Ini->_processSection()
#3 /var/www/vimbadmin/vendor/shardj/zf1-future/library/Zend/Config/Ini.php(163): Zend_Config_Ini->_processSection()
#4 /var/www/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application.php(421): Zend_Config_Ini->__construct()
#5 /var/www/vimbadmin/vendor/shardj/zf1-future/library/Zend/Application.php(103): Zend_Application->_loadConfig()
#6 /var/www/vimbadmin/bin/utils.inc(103): Zend_Application->__construct()
#7 /var/www/vimbadmin/bin/doctrine2-cli.php(53): get_zend_application()
#8 {main}
  thrown in /var/www/vimbadmin/vendor/shardj/zf1-future/library/Zend/Config/Ini.php on line 304
```

**Comment by mathiashro** [comment]
@frlan , did you solve the issue on your end? If yes, how?
