### ISSUE TITLE
Call to undefined function _()

### ISSUE THREAD

**Issue by DorianVL** [opensolutions/ViMbAdmin#312]
```
#0 /var/wwwroot/test.org/admin.mail/vendor/shardj/zf1-future/library/Zend/Form.php(239): ViMbAdmin_Form_Admin_AddEdit->init()
#1 /var/wwwroot/test.org/admin.mail/library/Twitter/Form.php(20): Zend_Form->__construct(NULL)
#2 /var/wwwroot/test.org/admin.mail/library/ViMbAdmin/Form.php(69): Twitter_Form->__construct(NULL)
#3 /var/wwwroot/test.org/admin.mail/application/controllers/AuthController.php(163): ViMbAdmin_Form->__construct()
#4 /var/wwwroot/test.org/admin.mail/vendor/shardj/zf1-future/library/Zend/Controller/Action.php(522): AuthController->setupAction()
#5 /var/wwwroot/test.org/admin.mail/vendor/shardj/zf1-future/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('setupAction')
#6 /var/wwwroot/test.org/admin.mail/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#7 /var/wwwroot/test.org/admin.mail/vendor/shardj/zf1-future/library/Zend/Application/Bootstrap/Bootstrap.php(106): Zend_Controller_Front->dispatch()
#8 /var/wwwroot/test.org/admin.mail/vendor/shardj/zf1-future/library/Zend/Application.php(400): Zend_Application_Bootstrap_Bootstrap->run()
#9 /var/wwwroot/test.org/admin.mail/public/index.php(34): Zend_Application->run()
#10 {main}
```

This happen after vimbadmin is connected to my pgsql_db when it tries to render a view during installation (url: /auth/setup)

Can repro with nginx + php-fpm config under
- php 8.1, 8.2 => docker container
- 8.3 => freebsd

**Comment by barryo** [comment]
Hi @DorianVL  - if you install the php-gettext extension you should be good here.
